<a href="https://colab.research.google.com/github/Nobunaga07/Contratos2/blob/main/Contratos2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd

In [ ]:
contratos = pd.read_csv("/content/drive/MyDrive/comprasnet-contratos-diario-cronogramas-latest.csv")

In [ ]:
contratos

            id  contrato_id  ... retroativo       valor
0     24732121        24728  ...        Não      340.83
1     24888537       115847  ...        Não     7500.00
2     24887490       115825  ...        Não     5686.00
3     24887036        38000  ...        Não    19870.27
4     24887964        36254  ...        Não      103.10
...        ...          ...  ...        ...         ...
8954  24902313       114588  ...        Não      626.70
8955  24900332       115978  ...        Não  4497240.61
8956  24902507         6705  ...        Não    72344.02
8957  24902421       114588  ...        Não      866.63
8958  24902413       114588  ...        Não        0.28

[8959 rows x 11 columns]

In [ ]:
contratos.loc[[0,1,2,3,4,5,6,7,8,9,10]]

          id  contrato_id  ... retroativo       valor
0   24732121        24728  ...        Não      340.83
1   24888537       115847  ...        Não     7500.00
2   24887490       115825  ...        Não     5686.00
3   24887036        38000  ...        Não    19870.27
4   24887964        36254  ...        Não      103.10
5   24887452       115821  ...        Não     3333.33
6   24887566       115828  ...        Não    83333.33
7   24886360         5787  ...        Não  1402510.03
8   24886997       115817  ...        Não     2281.25
9   24887038        38000  ...        Não     5071.40
10  24887445       115821  ...        Não     3333.33

[11 rows x 11 columns]

In [ ]:
contratos.loc[0:10]

          id  contrato_id  ... retroativo       valor
0   24732121        24728  ...        Não      340.83
1   24888537       115847  ...        Não     7500.00
2   24887490       115825  ...        Não     5686.00
3   24887036        38000  ...        Não    19870.27
4   24887964        36254  ...        Não      103.10
5   24887452       115821  ...        Não     3333.33
6   24887566       115828  ...        Não    83333.33
7   24886360         5787  ...        Não  1402510.03
8   24886997       115817  ...        Não     2281.25
9   24887038        38000  ...        Não     5071.40
10  24887445       115821  ...        Não     3333.33

[11 rows x 11 columns]